services:
    app:
        entrypoint:
            - sleep
            - infinity
        image: tictactoe
        init: true
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
