services:
    app:
        entrypoint:
            - sleep
            - infinity
        image: tictactoe
        environment:
            PORT: 9009
        ports:
            - 9009:9009
        init: true
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
